# Generated by Django 4.0.2 on 2022-02-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('todo', models.TextField(blank=True, null=True)),
                ('responsable', models.TextField(blank=True, null=True)),
                ('finish_at', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HG', 'High')], default='LW', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
