# Generated by Django 4.0.2 on 2022-02-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_body_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
